### ISSUE TITLE
Quality

### ISSUE THREAD

**Issue by dutchsing009** [SongtingLiu/VITS_voice_conversion#1]
Hello, I was wondering if you reached any groundbreaking quality with your method or at least the same quality as the many-to-many in the original vits demo , and if you can share the results

P.S about the architecture , I also thought about any-to-any vits before , it was to extract speaker embeddings from a pretrained speaker encoder like escapa tdnn and train on large dataset of so many speakers 1k+ and scale up the parameter.

Thanks in advance

**Comment by SongtingLiu** [comment]
Hi, thanks for you interest.
There is indeed something new to publish and the results are amazing. But this repo is not finished yet, and I'm still working on writing UI and testing the pipeline. Once it's done I'll notify you here.

**Comment by SongtingLiu** [comment]
It is now fully completed, have fun!
